### ISSUE TITLE
Adding comments to amazon_scrape.py

### ISSUE THREAD

**Issue by KBx4** [KBx4/Amazon-web-scraper#1]
### amazon_scrape.py is a program that scrapes the [Amazon India](https://www.amazon.in/) webpage.

_Workflow:_

- User is asked to enter the product they wanna search for
- User is given a top 10 list
- User can gain further information about any of the products

Two functions are there:

- products_page(): Retrieves top 10 products in the category user searched for
- product_info(): Retrieves information about the product selected

**Comment by prashantpadhy** [comment]
hey can you assign it to me

**Comment by KBx4** [comment]
> hey can you assign it to me

Assigned, thanks for the help
